#!/usr/bin/env bash
# bootstrap.sh — install dont-stop WITHOUT keeping a clone around.
#
# Use this when you do not want a checkout on the machine (devcontainers, throwaway
# boxes, or anywhere you would otherwise clone into /tmp and have the path vanish).
# It installs from the GitHub marketplace and wires the statusLine through a
# version-independent shim, so `claude plugin update` alone keeps everything
# current — nothing points at a path that can disappear or go stale.
#
#   bash bootstrap.sh              install / repair
#   bash bootstrap.sh --uninstall  remove the shim and statusLine wiring
#
# Safe to re-run. settings.json is backed up before any change.

set -euo pipefail

REPO="${DONT_STOP_REPO:-gry/claude-dont-stop}"
MARKET="claude-dont-stop"
PLUGIN="dont-stop@$MARKET"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
SETTINGS="${CLAUDE_SETTINGS:-$CLAUDE_DIR/settings.json}"
CFG="${CLAUDE_DONT_STOP_CONFIG:-$CLAUDE_DIR/dont-stop.json}"
SHIM="$CLAUDE_DIR/dont-stop-statusline"

command -v jq   >/dev/null || { echo "ERROR: jq is required"   >&2; exit 1; }
command -v curl >/dev/null || { echo "ERROR: curl is required" >&2; exit 1; }
command -v claude >/dev/null || { echo "ERROR: the 'claude' CLI is not on PATH" >&2; exit 1; }
mkdir -p "$CLAUDE_DIR"
[[ -f "$SETTINGS" ]] || echo '{}' > "$SETTINGS"

backup() { local b="$SETTINGS.bak.$(date +%Y%m%d%H%M%S)"; cp "$SETTINGS" "$b"; echo "backup: $b"; }

if [[ "${1:-}" == "--uninstall" ]]; then
  backup
  PREV=$(jq -r '.statuslineDelegate // empty' "$CFG" 2>/dev/null || true)
  tmp=$(mktemp)
  if [[ -n "$PREV" ]]; then
    jq --arg c "$PREV" '.statusLine = {type:"command", command:$c}' "$SETTINGS" > "$tmp"
    echo "restored your previous statusLine"
  else
    jq 'del(.statusLine)' "$SETTINGS" > "$tmp"
  fi
  mv "$tmp" "$SETTINGS"; rm -f "$SHIM"
  echo "shim removed. To drop the plugin too: claude plugin uninstall $PLUGIN"
  exit 0
fi

# --- 1. plugin from the marketplace -------------------------------------------
claude plugin marketplace add "$REPO" 2>/dev/null \
  || claude plugin marketplace update "$MARKET" 2>/dev/null || true
if claude plugin list 2>/dev/null | grep -q "$PLUGIN"; then
  claude plugin update "$PLUGIN" || true
else
  claude plugin install "$PLUGIN"
fi

# --- 2. version-independent shim ----------------------------------------------
# The plugin cache is version-pinned (…/dont-stop/1.0.3/…), so pointing settings
# straight at it would break on every update. This shim resolves the newest
# installed version at run time, which is what makes `claude plugin update` a
# complete upgrade path with nothing left to rewire by hand.
cat > "$SHIM" <<'SHIMEOF'
#!/usr/bin/env bash
# Resolves the newest installed dont-stop and hands the statusLine JSON to it.
# Generated by bootstrap.sh — safe to delete; re-run bootstrap.sh to recreate.
set -uo pipefail
BASE="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/plugins/cache/claude-dont-stop/dont-stop"
TARGET=""
if [[ -d "$BASE" ]]; then
  while IFS= read -r d; do
    [[ -x "$d/bin/dont-stop-statusline" ]] && { TARGET="$d/bin/dont-stop-statusline"; break; }
  done < <(ls -1d "$BASE"/*/ 2>/dev/null | sort -Vr)
fi
# No plugin found: stay out of the way rather than blanking the status line.
[[ -n "$TARGET" ]] || { cat >/dev/null; exit 0; }
exec "$TARGET"
SHIMEOF
chmod +x "$SHIM"
echo "statusline shim: $SHIM"

# --- 3. config + settings ------------------------------------------------------
[[ -f "$CFG" ]] || cat > "$CFG" <<'EOF'
{
  "enabled": true,
  "threshold": 95,
  "injectOnPrompt": true,
  "maxSleepSecs": 21600,
  "weeklyMaxWaitSecs": 28800,
  "graceSecs": 60
}
EOF

PREV=$(jq -r '.statusLine.command // empty' "$SETTINGS")
if [[ -n "$PREV" && "$PREV" != "$SHIM" ]]; then
  tmp=$(mktemp); jq --arg d "$PREV" '.statuslineDelegate = $d' "$CFG" > "$tmp" && mv "$tmp" "$CFG"
  echo "previous statusLine preserved as statuslineDelegate: $PREV"
fi
if [[ "$PREV" != "$SHIM" ]]; then
  backup
  tmp=$(mktemp)
  jq --arg s "$SHIM" '.statusLine = {type:"command", command:$s}' "$SETTINGS" > "$tmp" && mv "$tmp" "$SETTINGS"
fi

echo
claude plugin list 2>/dev/null | grep -A3 "dont-stop@" || true
echo
echo "Done. Restart Claude Code to load it."
echo "From now on, 'claude plugin update $PLUGIN' is the whole upgrade path."
